Repository gammaStrahlung/monopoly_app, pull requests merged in 2024-05, with the labels that each got.

#29 Websocket improvements
  app/src/main/java/at/gammastrahlung/monopoly_app/activities/LobbyActivity.java
  app/src/main/java/at/gammastrahlung/monopoly_app/game/Game.java
  app/src/main/java/at/gammastrahlung/monopoly_app/game/GameData.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/WebSocketClient.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/WebSocketHandler.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/dtos/ServerMessage.java
  app/src/test/java/at/gammastrahlung/monopoly_app/game/GameTest.java
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#31 Player info
  app/src/main/java/at/gammastrahlung/monopoly_app/adapters/FieldAdapter.java
  app/src/main/java/at/gammastrahlung/monopoly_app/fragments/PlayerInfoFragment.java
  app/src/main/java/at/gammastrahlung/monopoly_app/helpers/Fields.java
  app/src/main/res/drawable/list_border.xml
  app/src/main/res/layout/field_list_view.xml
  app/src/main/res/layout/fragment_playerinfo.xml
  app/src/main/res/layout/player_view.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/at/gammastrahlung/monopoly_app/helpers/FieldsTest.java
Labels: enhancement

#28 Display dice on gameboard
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/at/gammastrahlung/monopoly_app/activities/BoardActivity.java
  app/src/main/java/at/gammastrahlung/monopoly_app/activities/DiceRollingActivity.java
  app/src/main/java/at/gammastrahlung/monopoly_app/game/Dice.java
  app/src/main/java/at/gammastrahlung/monopoly_app/game/Game.java
  app/src/main/java/at/gammastrahlung/monopoly_app/game/GameData.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/MonopolyClient.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/WebSocketHandler.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/dtos/ServerMessage.java
  app/src/main/res/layout/activity_board.xml
  app/src/main/res/layout/dice_rolling.xml
  app/src/test/java/at/gammastrahlung/monopoly_app/game/DiceTest.java
  app/src/test/java/at/gammastrahlung/monopoly_app/game/GameDataTest.java
  app/src/test/java/at/gammastrahlung/monopoly_app/game/GameTest.java
Labels: enhancement

#34 Add null check to updatePlayerOnTurn()
  app/src/main/java/at/gammastrahlung/monopoly_app/activities/BoardActivity.java
Labels: bug

#36 Add android product flavors for websocket_uri
  app/build.gradle
  app/src/main/res/xml/network_security_config.xml
  gradle/libs.versions.toml
Labels: enhancement

#39 Fix SonarCloud
  app/build.gradle
Labels: bug

#40 Update README
  README.md
Labels: documentation

#37 Feature/move avatar UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/at/gammastrahlung/monopoly_app/activities/BoardActivity.java
  app/src/main/java/at/gammastrahlung/monopoly_app/activities/DiceRollingActivity.java
  app/src/main/java/at/gammastrahlung/monopoly_app/activities/MainActivity.java
  app/src/main/java/at/gammastrahlung/monopoly_app/fragments/FieldFragment.java
  app/src/main/java/at/gammastrahlung/monopoly_app/game/Player.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/MonopolyClient.java
  app/src/main/java/at/gammastrahlung/monopoly_app/network/WebSocketHandler.java
  app/src/main/res/layout/activity_main.xml
  app/src/test/java/at/gammastrahlung/monopoly_app/game/PlayerTest.java
Labels: enhancement
